import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from './components/Sidebar';  // Import the Sidebar component
import './globals.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex">
          {/* Sidebar Component */}
          <Sidebar />

          {/* Main Content Area */}
          <div className="flex-1 p-6">
            {/* Render the page content here */}
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}

